	QsysSystem u0 (
		.clk_clk                                    (<connected-to-clk_clk>),                                    //                                 clk.clk
		.green_leds_external_connection_export      (<connected-to-green_leds_external_connection_export>),      //      green_leds_external_connection.export
		.keys_external_connection_export            (<connected-to-keys_external_connection_export>),            //            keys_external_connection.export
		.red_leds_external_connection_export        (<connected-to-red_leds_external_connection_export>),        //        red_leds_external_connection.export
		.reset_reset                                (<connected-to-reset_reset>),                                //                               reset.reset
		.sd_b_SD_cmd                                (<connected-to-sd_b_SD_cmd>),                                //                                  sd.b_SD_cmd
		.sd_b_SD_dat                                (<connected-to-sd_b_SD_dat>),                                //                                    .b_SD_dat
		.sd_b_SD_dat3                               (<connected-to-sd_b_SD_dat3>),                               //                                    .b_SD_dat3
		.sd_o_SD_clock                              (<connected-to-sd_o_SD_clock>),                              //                                    .o_SD_clock
		.sdram_clk_clk                              (<connected-to-sdram_clk_clk>),                              //                           sdram_clk.clk
		.sdram_wire_addr                            (<connected-to-sdram_wire_addr>),                            //                          sdram_wire.addr
		.sdram_wire_ba                              (<connected-to-sdram_wire_ba>),                              //                                    .ba
		.sdram_wire_cas_n                           (<connected-to-sdram_wire_cas_n>),                           //                                    .cas_n
		.sdram_wire_cke                             (<connected-to-sdram_wire_cke>),                             //                                    .cke
		.sdram_wire_cs_n                            (<connected-to-sdram_wire_cs_n>),                            //                                    .cs_n
		.sdram_wire_dq                              (<connected-to-sdram_wire_dq>),                              //                                    .dq
		.sdram_wire_dqm                             (<connected-to-sdram_wire_dqm>),                             //                                    .dqm
		.sdram_wire_ras_n                           (<connected-to-sdram_wire_ras_n>),                           //                                    .ras_n
		.sdram_wire_we_n                            (<connected-to-sdram_wire_we_n>),                            //                                    .we_n
		.sevseg4msb_external_connection_export      (<connected-to-sevseg4msb_external_connection_export>),      //      sevseg4msb_external_connection.export
		.sevsegment_4lsb_external_connection_export (<connected-to-sevsegment_4lsb_external_connection_export>), // sevsegment_4lsb_external_connection.export
		.sram_DQ                                    (<connected-to-sram_DQ>),                                    //                                sram.DQ
		.sram_ADDR                                  (<connected-to-sram_ADDR>),                                  //                                    .ADDR
		.sram_LB_N                                  (<connected-to-sram_LB_N>),                                  //                                    .LB_N
		.sram_UB_N                                  (<connected-to-sram_UB_N>),                                  //                                    .UB_N
		.sram_CE_N                                  (<connected-to-sram_CE_N>),                                  //                                    .CE_N
		.sram_OE_N                                  (<connected-to-sram_OE_N>),                                  //                                    .OE_N
		.sram_WE_N                                  (<connected-to-sram_WE_N>),                                  //                                    .WE_N
		.switches_external_connection_export        (<connected-to-switches_external_connection_export>),        //        switches_external_connection.export
		.vga_out_CLK                                (<connected-to-vga_out_CLK>),                                //                             vga_out.CLK
		.vga_out_HS                                 (<connected-to-vga_out_HS>),                                 //                                    .HS
		.vga_out_VS                                 (<connected-to-vga_out_VS>),                                 //                                    .VS
		.vga_out_BLANK                              (<connected-to-vga_out_BLANK>),                              //                                    .BLANK
		.vga_out_SYNC                               (<connected-to-vga_out_SYNC>),                               //                                    .SYNC
		.vga_out_R                                  (<connected-to-vga_out_R>),                                  //                                    .R
		.vga_out_G                                  (<connected-to-vga_out_G>),                                  //                                    .G
		.vga_out_B                                  (<connected-to-vga_out_B>)                                   //                                    .B
	);

